src/Entity/Sentence.php
<?php

namespace App\Entity;

use App\Repository\SentenceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SentenceRepository::class)
 */
class Sentence
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Concept;
use App\Entity\Parameters;
use App\Entity\Sentence;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default")
     */
    public function index(): Response
    {
        $parameters = null;
        $parameter_name = $_ENV['PARAMETER'];
        if (!is_null($parameter_name)) {
            $parameters = $this->getDoctrine()->getRepository(Parameters::class)->findOneBy([
                'name' => $parameter_name
            ]);
        }

        // Récupération de la dernière notion (concept) ajoutée
        $concept = $this->getDoctrine()->getRepository(Concept::class)->last();

        // Récupération des phrases du jour
        $sentences = $this->getDoctrine()->getRepository(Sentence::class)->findAll(); 

        // On génère un tableau de phrase avec pour index leur id
        $tabSentences = [];
        foreach ($sentences as $sentence)
        {
            $tabSentences[$sentence->getId()] = $sentence;
        }

        // On récupère au hazard une phrase
        $random = array_rand($tabSentences, 1);

        return $this->render('default/index.html.twig', [
            'concept' =>  $concept,
            'sentence' => $tabSentences[$random],
            'parameters' => $parameters
        ]);
    }

    /**
     * @Route("/concept/show/{id}", name="concept_show", requirements={"id": "\d+"})
     */
    public function show(Request $request, $id)
    {
        $concept = $this->getDoctrine()->getRepository(Concept::class)->find($id);

        if (is_null ($concept)) {
            throw $this->createNotFoundException('La notion recherchée n\'existe pas !!!');
        }

        if ($concept->getIsDraft() === true) {
            $this->denyAccessUnlessGranted('ROLE_ADMIN');
        }

        return $this->render('default/show.html.twig', [
            'concept' => $concept
        ]);
    }

    /**
     * @Route("/references", name="references")
     */
    public function references()
    {
        $references = null;
        $parameter_name = $_ENV['PARAMETER'];
        $parameters = $this->getDoctrine()->getRepository(Parameters::class)->findOneBy([
            'name' => $parameter_name
        ]);

        if (!is_null($parameters)) {
            $references = $parameters->getReferences();
        }
        
        return $this->render('default/references.html.twig', [
            'references' => $references
        ]);

    }
}

templates/default/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}À propos{% endblock %}

{% block body %}
    <div class="container">
        etsruiaetuianetaui
    </div>
{% endblock %}

templates/default/connaissances.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingrédient Technique{% endblock %}

{% block body %}
    <div class="container">

        <h3>Les connaissances nécessaires</h3>
        <div class="row d-flex justify-content-center">
            <div class="col-md-2 border border-1 mr-2">
                <h4 class="text-center">HTML</h4>
            </div>
            <div class="col-md-2 border border-1 mr-2">
                <h4 class="text-center">CSS</h4>
            </div>
            <div class="col-md-2 border border-1 mr-2">
                <h4 class="text-center">JAVASCRIPT</h4>
            </div>
            <div class="col-md-2 border border-1">
                <h4 class="text-center">PHP</h4>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingrédient Technique{% endblock %}

{% block body %}
    <div class="container">

    </div>
{% endblock %}

templates/default/footer.html.twig
<footer>
    <div class="leftArea">
        
    </div>
    <div class="centerArea">
        <h3>&copy; Ingrédient Technique</h3>
    </div>
    <div class="rightArea">
        <ul>
            <li><a href="#">À propos</a></li>
            <li><a href="">politique de confidentialité</a></li>
        </ul>
    </div>
</footer>

templates/default/historique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingrédient Technique{% endblock %}

{% block body %}
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h3>Historique</h3>
                <h5>semaine 50 (7 au 13 déc 2020)</h5>
                <ul>
                    <li>Choix d'un hébergement Web et nom de domaine</li>
                    <li>Création d'un dépôt github</li>
                    <li>Création du projet symfony avec Symfony-cli</li>
                    <li>Installation des composants make template annotation</li>
                    <li>Création de la première page uniquement en HTML</li>
                    <li>Ajout du framework Bootstrap</li>
                    <li>Ajout d'une barre de navigation</li>
                    <li>Ajout d'un jumbotron</li>
                    <li>Structure de la page avec un header et footer</li>
                    <li>Création de cartes Bootstrap</li>
                    <li>Création des pages à propos, historique, contact, outils et connaissances</li>

                    <p>Pour le moment je ne m'occupe que de la partie statique du site</p>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingrédient Technique{% endblock %}
{% block body %}
    <header class="header-jumbotron">
            <div class="area-presentation">
                <p>
                Bienvenue sur le site d'Ingrédient Technique. <br>
                Un site qui parle de développement Web
                </p>
            </div>
            <div class="area-sentence">
                <div class="sentence">
                    <span>Ready
                    &#9632;</span>
                    <p>{{ sentence.content|raw }}</p>
                    <blockquote class="text-right">{{ sentence.author }}</blockquote>
                </div>
            </div>
    </header>
    <div class="wrapper">
        <h1>En construction</h1>

        <p>
            <iframe src="https://giphy.com/embed/LqMn3zJKoi93O"
            frameBorder="0" class="giphy-embed" allowFullScreen>
            </iframe><p><a href="https://giphy.com/gifs/internet-cartoon-computer-LqMn3zJKoi93O">via GIPHY</a></p>
        </p>
    </div>          
{% endblock %}

templates/default/outils.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingrédient Technique{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Les outils</h3>
                <ul>
                    <li>Un ordinateur</li>
                    <li>IDE</li>
                    <li>XAMPP</li>
                    <li>Émulateur console</li>
                    <li>Une connexion internet</li>
                    <li>De la motivation</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/references.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingrédient Technique{% endblock %}
{% block body %}
    
    <div class="wrapper">
    <h4>Références</h4>

    <p>
    {% if references is defined %}
        {{ references }}
    {% endif %}
    </p>
    </div>          
    
{% endblock %}

templates/default/show.html.twig
{# templates/default/show.html.twig #}

{% extends('base.html.twig') %}

{% block title %}Notion{% endblock %}

{% block body %}
    <div class="container bg-light shadow border border-1 p-3" style="margin-top: 100px;">
        <div class="row">
            <div class="col-md-8">
                <h4>{{ concept.title }} </h4>
            </div>
            <div class="col-md-4">
                <span class="badge badge-primary">Crée le {{ concept.createdAt|date('d/m/Y') }}</span>
                <span class="badge badge-success">Mis à jour le {{ concept.updatedAt|date('d/m/Y') }}</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                {{ concept.description }}
            </div>
            <div class="col-md-4">
                {{ concept.theme.title }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {{ concept.content|raw }}
            </div>
        </div>
    </div>
{% endblock %}